export type Settings = {
	["botIndex"]: number;
	["botVolumes"]: Record<string, number>;
	["queue.showThumbnail"]: boolean;
	["notification.browser"]: boolean;
	["notification.inApp"]: boolean;
	["discord.richPresence.template"]: string;
	["discord.richPresence.idleTemplate"]: string;
	["discord.richPresence"]: boolean;
	["discord.rpc"]: boolean;
	["discord.rpcClientId"]: string;
	["discord.rpcClientSecret"]: string;
	["app.drawerSize"]: number;
	["app.catJam.enabled"]: boolean;
	["app.player.size"]: number;
	["app.player.minimized"]: boolean;
	["app.textSize"]: number;
	["app.snowfall.enabled"]: boolean;
	["app.snowfall.amount"]: number;
	["app.snowfall.speed"]: number;
	["app.mediaSession.enabled"]: boolean;
	["overlay.enabled"]: boolean;
	["overlay.shortcut"]: string[];
	["overlay.nowPlaying.enabled"]: boolean;
	["overlay.nowPlaying.opacity"]: number;
	["overlay.nowPlaying.position"]: "tl" | "tr" | "bl" | "br";
	["overlay.nowPlaying.size"]: "sm" | "md" | "lg";
	["overlay.catJam.enabled"]: boolean;
	["spotify.enabled"]: boolean;
	["spotify.clientId"]: string;
};
